- name: Create Node Exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /opt/node_exporter
    - /var/lib/node_exporter

- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/node_exporter
    remote_src: yes

- name: Move Node Exporter binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv /opt/node_exporter/node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/
  args:
    creates: /usr/local/bin/node_exporter

- name: Set permissions for Node Exporter binary
  file:
    path: /usr/local/bin/node_exporter
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/node_exporter \
        --log.level=info \
        --web.listen-address="0.0.0.0:9100"
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon for Node Exporter
  command: systemctl daemon-reload

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started