- name: Download PostgreSQL Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/postgres_exporter.tar.gz

- name: Extract PostgreSQL Exporter
  ansible.builtin.unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move PostgreSQL Exporter binary
  ansible.builtin.command:
    cmd: mv /opt/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter /usr/local/bin/
    creates: /usr/local/bin/postgres_exporter

- name: Create PostgreSQL Exporter systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/postgres_exporter.service
    content: |
      [Unit]
      Description=PostgreSQL Exporter
      Wants=postgresql.service
      After=postgresql.service

      [Service]
      User=postgres
      Group=postgres
      ExecStart=/usr/local/bin/postgres_exporter \
        --extend.query-path=/etc/postgres/queries.yaml \
        --web.listen-address=0.0.0.0:9187 \
        --web.telemetry-path=/metrics
      Environment=DATA_SOURCE_NAME=postgresql://postgres:password@localhost:5432/?sslmode=disable

      [Install]
      WantedBy=multi-user.target

  register: postgres_service_status

- name: Restart PostgreSQL Exporter service if changed
  ansible.builtin.systemd:
    name: postgres_exporter
    state: restarted
    enabled: true
    when: postgres_service_status is changed

- name: Install custom queries for PostgreSQL Exporter
  ansible.builtin.template:
    src: queries.yaml
    dest: /etc/postgres/queries.yaml
    owner: postgres
    group: postgres
    mode: 0644