---
# Создаем директорию для PostgreSQL Exporter
- name: Create Postgres Exporter directory
  file:
    path: /opt/postgres_exporter
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download PostgreSQL Exporter
  get_url:
    url: https://github.com/prometheus-community/postgres_exporter/releases/download/v0.10.1/postgres_exporter-0.10.1.linux-amd64.tar.gz
    dest: /tmp/postgres_exporter.tar.gz

- name: Extract PostgreSQL Exporter
  unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /opt/postgres_exporter
    remote_src: yes

- name: Move PostgreSQL Exporter binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv /opt/postgres_exporter/postgres_exporter-0.10.1.linux-amd64/postgres_exporter /usr/local/bin/
  args:
    creates: /usr/local/bin/postgres_exporter

- name: Set permissions for PostgreSQL Exporter binary
  file:
    path: /usr/local/bin/postgres_exporter
    owner: root
    group: root
    mode: '0755'

- name: Create PostgreSQL Exporter service configuration
  copy:
    dest: /etc/systemd/system/postgres_exporter.service
    content: |
      [Unit]
      Description=PostgreSQL Exporter
      After=network.target

      [Service]
      Environment=DATA_SOURCE_NAME="postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable" 
      ExecStart=/usr/local/bin/postgres_exporter \
        --web.listen-address=:{{ postgres_exporter_port }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and enable PostgreSQL Exporter
  systemd:
    name: postgres_exporter
    enabled: true
    state: started