---
# Копируем бинарный файл etcd_exporter
- name: Copy etcd_exporter binary
  copy:
    src: roles/etcd_exporter/files/etcd
    dest: /usr/local/bin/etcd_exporter
    mode: '0755'

# Создаем systemd unit для etcd_exporter
- name: Create etcd_exporter systemd service
  copy:
    dest: /etc/systemd/system/etcd_exporter.service
    content: |
      [Unit]
      Description=ETCD Exporter
      Documentation=https://github.com/prometheus-community/etcd_exporter
      After=network.target

      [Service]
      User=root
      Group=root
      ExecStart=/usr/local/bin/etcd_exporter --etcd.endpoint=http://localhost:2379
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

# Включаем и запускаем etcd_exporter через systemd
- name: Reload systemd to apply changes
  command: systemctl daemon-reload

- name: Start and enable etcd_exporter
  systemd:
    name: etcd_exporter
    state: started
    enabled: yes