---
- name: Create Blackbox Exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /opt/blackbox_exporter
    - /etc/blackbox_exporter
    - /var/lib/blackbox_exporter

- name: Download Blackbox Exporter
  get_url:
    url: "https://github.com/prometheus/blackbox_exporter/releases/download/v0.23.0/blackbox_exporter-0.23.0.linux-amd64.tar.gz"
    dest: /tmp/blackbox_exporter.tar.gz

- name: Extract Blackbox Exporter
  unarchive:
    src: /tmp/blackbox_exporter.tar.gz
    dest: /opt/blackbox_exporter
    remote_src: yes

- name: Move Blackbox Exporter binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv /opt/blackbox_exporter/blackbox_exporter-0.23.0.linux-amd64/blackbox_exporter /usr/local/bin/
  args:
    creates: /usr/local/bin/blackbox_exporter

- name: Set permissions for Blackbox Exporter binary
  file:
    path: /usr/local/bin/blackbox_exporter
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Deploy Blackbox Exporter configuration file
  template:
    src: blackbox.yml.j2
    dest: /etc/blackbox_exporter/config.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create Blackbox Exporter systemd service
  copy:
    dest: /etc/systemd/system/blackbox_exporter.service
    content: |
      [Unit]
      Description=Blackbox Exporter
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/blackbox_exporter \
        --config.file=/etc/blackbox_exporter/config.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon for Blackbox Exporter
  command: systemctl daemon-reload

- name: Start and enable Blackbox Exporter
  systemd:
    name: blackbox_exporter
    enabled: yes
    state: started