all:
  children:
    prometheus:
      hosts:
        monitoring_server:
          ansible_host: 176.109.82.213
          ansible_port: 29022
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
    postgres:
      hosts:
        192.168.1.54:
          ansible_host: 176.109.82.213
          ansible_port: 29023
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
        192.168.1.55:
          ansible_host: 176.109.82.213
          ansible_port: 29024
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
    etcd:
      hosts:
        192.168.1.56:
          ansible_host: 176.109.82.213
          ansible_port: 29025
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
        192.168.1.57:
          ansible_host: 176.109.82.213
          ansible_port: 29026
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
        192.168.1.58:
          ansible_host: 176.109.82.213
          ansible_port: 29027
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
    blackbox:
      hosts:
        192.168.1.53:
          ansible_host: 176.109.82.213
          ansible_port: 29022
          ansible_user: muostapchuk
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn
    os_metrics:
      hosts:
        monitoring_server:
          ansible_host: 176.109.82.213
          ansible_ssh_private_key_file: ~/.ssh/id_sre_learn